version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies"
      - npm ci
      - npm install mssql

  build:
    commands:
      - echo "Building the application"
      - npm run build

artifacts:
  files:
    - '**/*'
    - '!node_modules/**/*'
    - '!build/**/*'
