version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing npm dependencies"
      - npm install
    post_build:
      commands:
        - echo "Adding additional dependencies"
        - npm install mssql@10.0.2
        - npm install serverless-offline@13.3.3
        - npm install sql@0.78.0

build:
  commands:
    - echo "Running build commands"
    - npm run build
     - zip -r build/artifacts.zip *
    

artifacts:
  files:
    - artifacts.zip
    
